INSERT INTO Competence(com_reference, com_libelle, com_description ,com_obligatoire) VALUES
(NULL, 'Participation à un projet d’évolution d’un SI (solution applicative et d’infrastructure portant prioritairement sur le domaine de spécialité du candidat)', 'desc' ,1),
(NULL, 'Prise en charge d’incidents et de demandes d’assistance liés au domaine de spécialité du candidat', 'desc' ,1),
(NULL, 'Elaboration de documents relatifs à la production et à la fourniture de services', 'desc' ,1),
(NULL, 'Productions relatives à la mise en place d’un dispositif de veille technologique et à l’étude d’une technologie, d’un composant, d’un outil ou d’une méthode', 'desc' ,1),
('A1.1.1', 'Analyse du cahier des charges d''un service à produire', 'desc' ,0),
('A1.1.2', 'Étude de l''impact de l''intégration d''un service sur le système informatique','desc',0),
('A1.1.3', 'Étude des exigences liées à la qualité attendue d''un service','desc',0),
('A1.2.1', 'Élaboration et présentation d''un dossier de choix de solution technique','desc',0),
('A1.2.2', 'Rédaction des spécifications techniques de la solution retenue','desc',0),
('A1.2.3', 'Évaluation des risques liés à l''utilisation d''un service','desc',0),
('A1.2.4', 'Détermination des tests nécessaires à la validation d''un service','desc',0),
('A1.2.5', 'Définition des niveaux d''habilitation associés à un service','desc',0),
('A1.3.1', 'Test d''intégration et d''acceptation d''un service','desc',0),
('A1.3.2', 'Définition des éléments nécessaires à la continuité d''un service','desc',0),
('A1.3.3', 'Accompagnement de la mise en place d''un nouveau service','desc',0),
('A1.3.4', 'Déploiement d''un service', 'desc' ,0),
('A1.4.1', 'Participation à un projet', 'desc' ,0),
('A1.4.2', 'Évaluation des indicateurs de suivi d''un projet et justification des écarts', 'desc' ,0),
('A1.4.3', 'Gestion des ressources', 'desc' ,0),
('A2.1.1', 'Accompagnement des utilisateurs dans la prise en main d''un service', 'desc' ,0),
('A2.1.2', 'Évaluation et maintien de la qualité d''un service', 'desc' ,0),
('A2.2.1', 'Suivi et résolution d''incidents', 'desc' ,0),
('A2.2.2', 'Suivi et réponse à des demandes d''assistance', 'desc' ,0),
('A2.2.3', 'Réponse à une interruption de service', 'desc' ,0),
('A2.3.1', 'Identification, qualification et évaluation d''un problème', 'desc' ,0),
('A2.3.2', 'Proposition d''amélioration d''un service', 'desc' ,0),
('A3.1.1', 'Installation et configuration d’éléments d’infrastructure ','desc', 0),
('A3.1.2', 'Maquettage et prototypage d’une solution d’infrastructure','desc', 0),
('A3.1.3', 'Prise en compte du niveau de sécurité nécessaire à une infrastructure ','desc', 0),
('A3.2.1', 'Installation et configuration d''éléments d''infrastructure ','desc', 0),
('A3.2.2', 'Remplacement ou mise à jour d''éléments défectueux ou obsolètes','desc', 0),
('A3.2.3', 'Mise à jour de la documentation technique d’une solution d’infrastructure\r\n','desc', 0),
('A3.3.1', 'Administration sur site ou à distance des éléments d’un réseau, de serveurs, de services et d’équipements terminaux','desc', 0),
('A3.3.2', 'Appliquer des procédures de sauvegarde et de restauration','desc', 0),
('A3.3.3', 'Gestion des identités et des habilitations\r\n','desc', 0),
('A3.3.4', 'Automatisation des tâches d’administration\r\n','desc', 0),
('A3.3.5', 'Gestion des indicateurs et des fichiers d’activité\r\n','desc', 0),
('A4.1.1', 'Proposition d''une solution applicative','desc', 0),
('A4.1.2', 'Conception ou adaptation de l''interface utilisateur d''une solution applicative','desc', 0),
('A4.1.3', 'Conception ou adaptation d''une base de données','desc', 0),
('A4.1.4', 'Définition des caractéristiques d''une solution applicative','desc', 0),
('A4.1.5', 'Prototypage de composants logiciels','desc', 0),
('A4.1.6', 'Gestion d''environnements de développement et de test','desc', 0),
('A4.1.7', 'Développement, utilisation ou adaptation de composants logiciels','desc', 0),
('A4.1.8', 'Réalisation des tests nécessaires à la validation d''éléments adaptés ou développés ','desc', 0),
('A4.1.9', 'Rédaction d''une documentation technique ','desc', 0),
('A4.1.1', ' Rédaction d''une documentation d''utilisation ','desc', 0),
('A4.2.1', 'Analyse et correction d''un dysfonctionnement, d''un problème de qualité de …','desc', 0),
('A4.2.2', 'Adaptation d''une solution applicative aux évolutions de ses composants','desc', 0),
('A4.2.3', 'Réalisation des tests nécessaires à la mise en production d''éléments mis à jour','desc', 0),
('A4.2.4', 'Mise à jour d''une documentation technique','desc', 0),
('A5.1.1', 'Mise en place d''une gestion de configuration','desc', 0),
('A5.1.2', 'Recueil d''informations sur une configuration et ses éléments','desc', 0),
('A5.1.3', 'Suivi d''une configuration et de ses éléments','desc', 0),
('A5.1.4', 'Étude de propositions de contrat de service (client, fournisseur)','desc', 0),
('A5.1.5', 'Évaluation d''un élément de configuration ou d''une configuration ','desc', 0),
('A5.1.6', 'Évaluation d''un investissement informatique','desc', 0),
('A5.2.1', 'Exploitation des référentiels, normes et standards adoptés par le prestataire','desc', 0),
('A5.2.2', 'Veille technologique','desc', 0),
('A5.2.3', 'Repérage des compléments de formation ou d''auto-formation','desc', 0),
('A5.2.4', 'Étude d‘une technologie, d’un composant, d’un outil ou d’une méthode','desc', 0);

